compatibility_date = "2024-09-23"
name = "randombits"
pages_build_output_dir = './dist'

kv_namespaces = [
  { binding = "KV", id = "8e38477589fc49fb90505b7d3be9da3e" }
]

[env.preview]

kv_namespaces = [
  { binding = "KV", id = "8ac3fa0d5ca448a08eab712494b03ccb" }
]
